### ISSUE TITLE
Land cover one hot reshape problem

### ISSUE THREAD

**Issue by riccardodelutio** [maximiliense/GLC#7]
Hi, 

I was trying out the code you provided for creating a pytorch dataset and dataloader, (which is very helpful, thanks) [https://github.com/maximiliense/GLC/blob/master/examples/pytorch_dataset.py](url).

I just encountered a small issue in the land cover one hot encoding, it seems like there is a problem when reshaping it in the `__getitem__` method of the `DatasetGLC20` class.

In fact when having a look at the sample `10000000` from the France training dataset, which looks like this before the one-hot:
![no_onehot](https://user-images.githubusercontent.com/19930396/80200165-86650980-8622-11ea-8833-f442a87ab00d.png)

After doing the one-hot encoding it looks like this:
![one_hot](https://user-images.githubusercontent.com/19930396/80201498-87973600-8624-11ea-9a76-4e9663b8bcbf.png)

I made a small change to the `__getitem__` method to fix this such that it looks like this:
![fixed_one_hot](https://user-images.githubusercontent.com/19930396/80201490-81a15500-8624-11ea-88bd-3e3526acb1db.png)

```
lc = rgb_ir_lc[4:5][0]    
lc_one_hot = np.zeros((self.one_hot_size,lc.shape[0], lc.shape[1]))
layer_idx = np.arange(lc.shape[0]).reshape(lc.shape[0], 1)
component_idx = np.tile(np.arange(lc.shape[1]), (lc.shape[0], 1))
lc_one_hot[lc, layer_idx, component_idx] = 1
```

I can open a pull request if that would help. 

Cheers,
Riccardo

**Comment by maximiliense** [comment]
Dear Riccado, Yes thank you very much, I would be glad if you could open a pull request! Thanks!

**Comment by riccardodelutio** [comment]
Great, just opened it!

**Comment by maximiliense** [comment]
Thx! I merged your pull request!
